console.log(document);
const h1El = document.querySelector('h1');
console.log(h1El);
const aboutUsEl = document.querySelector(`#aboutUs`);
console.log(aboutUsEl);
const spanEl = document.querySelector(`#aboutUs span`);
console.log(spanEl);
const menuEl = document.querySelector(`ul.menu`);
console.log(menuEl);
const menuItem3 = document.querySelector(`ul.menu li:nth-child(3)`);
console.log(menuItem3);
